FROM docker:29.3.1-alpine3.23@sha256:4d90f1f6c400315c2dba96d3ec93c01e64198395cbba04f79d12adce4f737029

# Install system packages including compression tools and gffread
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.23/main" > /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/v3.23/community" >> /etc/apk/repositories && \
    apk update && apk add --no-cache \
    sudo \
    openssh-client \
    vim \
    
    less \
    gzip \
    pigz \
    && adduser -D -u 1000 -s /bin/sh vscode \
    && mkdir -p /etc/sudoers.d \
    && echo "vscode ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vscode \
    && chmod 0440 /etc/sudoers.d/vscode \
    && chown -R vscode:vscode /home/vscode

# Switch to the vscode user by default
USER vscode
WORKDIR /EFSA_workspace